[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "frost"
authors = [{name = "Benjamin Moran", email = "benmoran@protonmail.com"}]
readme = "README.md"
license = {file = "LICENSE.md"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version"]
requires-python = ">=3.8"
dependencies = ["pyglet"]

[project.urls]
Home = "https://github.com/benmoran56/frost"

[tool.hatch.version]
path = "frost/__init__.py"
